"""Mise à jour des modèles : ajout de commentaires, nullable, quantités, etc.

Revision ID: cdc9f66cdf06
Revises: 7295bf964176
Create Date: 2025-04-02 18:31:02.401329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc9f66cdf06'
down_revision = '7295bf964176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achat', schema=None) as batch_op:
        batch_op.alter_column('date_achat',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('commandeproduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))
        batch_op.alter_column('date_cp',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('lignereception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('reception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))
        batch_op.alter_column('date_reception',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reception', schema=None) as batch_op:
        batch_op.alter_column('date_reception',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('commentaire')

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('lignereception', schema=None) as batch_op:
        batch_op.drop_column('commentaire')

    with op.batch_alter_table('commandeproduction', schema=None) as batch_op:
        batch_op.alter_column('date_cp',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('commentaire')

    with op.batch_alter_table('achat', schema=None) as batch_op:
        batch_op.alter_column('date_achat',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
